### ISSUE TITLE
Missing latest CVE Security Fix

### ISSUE THREAD

**Issue by scafroglia93** [OnePlusOSS/android_kernel_oneplus_msm8996#10]
Well Done Oneplus!

![schermata del 2016-11-16 02-16-23](https://cloud.githubusercontent.com/assets/8227101/20332891/4320a798-abaf-11e6-9e3a-dedf8c454d8c.png)
![schermata del 2016-11-16 02-37-02](https://cloud.githubusercontent.com/assets/8227101/20332894/459dc2f8-abaf-11e6-9b44-681147e5819e.png)

**Comment by jcadduono** [comment]
don't forget your dirty cows!
i rebased and made updates and fixes on my fork: https://github.com/jcadduono/android_kernel_oneplus_msm8996/commits/3T-android-6.0

not sure if it boots though :) lots of changes since sept 6th and i don't own the device, probably never will as there might be something else with a 4K screen on the horizon, i love my VR

going from OnePlus 3's history, it looks like OnePlus doesn't even bother with any kernel commits. they just grab a CAF tag and roll with it forever lol. maybe the kernel security fixes will never reach the device.

at least in nougat they'll probably need to grab another CAF tag, but it might not be any more up to date than the current one theyre using heh.

**Comment by NewEraCracker** [comment]
Why not opening PRs via https://github.com/OnePlusOSS/android_kernel_oneplus_msm8996/pulls and also informing 3rd party kernel authors about this?

There are some popular 3rd party kernels that care more about security and work well over the stock version. I am presently using one of those after doing source code audits.

**Comment by NewEraCracker** [comment]
OnePlus customers really need to exert pressure on them so the software team does their job properly.

I have submitted a few pull requests and I recommend anyone with security knowledge to actively hunt and propose fixes for security vulnerabilities.

**Update**: All security-related commits are now at: #16

**Comment by scafroglia93** [comment]
October 2016 WTF hahaha

![schermata del 2016-11-21 21-38-00](https://cloud.githubusercontent.com/assets/8227101/20499763/2fc0b21e-b033-11e6-8b0e-1354301c0411.png)
